settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.gregbrimble.workers.dev'
  logo: logo-192x192.png
  daysInHistogram: 28

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: gregbrimble-com
    name: gregbrimble.com
    url: 'https://gregbrimble.com/'
